<a href="https://colab.research.google.com/github/vishv96/TensorFlow/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
0.# Introduction to TensorFlow

0.0

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# "ndim" to find number of dimentions
scalar.ndim

0

In [ ]:
# Creating a vector
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
# Finding dimention of vector
vector.ndim

1

In [ ]:
# Creating a mattrix
matrix = tf.constant([[10,7],
                       [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [4.,5.],
                              [9.,4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 4.,  5.],
       [ 9.,  4.]], dtype=float16)>

In [ ]:
# Dimention of another_matrix
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[
    [1,3,4],
    [2,8,6],
    [9,2,7]
],[
    [3,4,7],
     [0,3,1],
  [5,7,3]
    ], [[2,32,55], [4,6,8], [7,44,56]]], dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  3,  4],
        [ 2,  8,  6],
        [ 9,  2,  7]],

       [[ 3,  4,  7],
        [ 0,  3,  1],
        [ 5,  7,  3]],

       [[ 2, 32, 55],
        [ 4,  6,  8],
        [ 7, 44, 56]]], dtype=int32)>